version: '3.8'

services:
  frontend:
    image: httpd:2.4
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
      - ./frontend/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./frontend/apache-proxy.conf:/usr/local/apache2/conf/extra/httpd-proxy.conf
    networks:
      - frontend
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=anime_db
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anime_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - backend

networks:
  frontend:
  backend:
