build:
	docker build --rm -t hadoop-hive-spark-base ./base
	docker build --rm -t hadoop-hive-spark-master ./master
	docker build --rm -t hadoop-hive-spark-worker ./worker
	docker build --rm -t hadoop-hive-spark-history ./history
	# docker build --rm -t hadoop-hive-spark-jupyter ./jupyter