version: '3.8'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  frontend:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=anime_db
    volumes:
      - .:/app
      - ./backend:/app/backend
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anime_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
